version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    groups:
      pip-patch-minor:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      pip-dev:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "UTC"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
